@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package ttmp.infernoreborn.util.damage;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;