@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package ttmp.infernoreborn.contents.sigil;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;