@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package ttmp.wtf.definitions.initializer;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;