@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package ttmp.infernoreborn.compat.patchouli.sigil;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;