@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package ttmp.cafscript.definitions.initializer;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;