@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package ttmp.infernoreborn.contents.entity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;