@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package ttmp.infernoreborn.contents.effect;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;